language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm
  - nightly
env:
  - COMPOSER_OPTS=""

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

sudo: false

install:
  - 'if [ $(phpenv version-name) == "5.5" ]; then rm ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini; fi'
  - 'if [ $(phpenv version-name) != "hhvm" ] && [ $(phpenv version-name) != "nightly" ]; then echo "xdebug.overload_var_dump = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - composer --version
  - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source --profile

script:
  - phpunit --colors=always

after_success:
  - bash <(curl -s https://codecov.io/bash)
